[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
jgfxlib = { path = "../jgfxlib" }
rand = {version = "0.8.5", features = ["small_rng"] }
xorshift = "0.1.3"
fastrand = "1.8.0"
